# Generated by Django 5.2.8 on 2025-11-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=140)),
                ('modelo', models.CharField(max_length=140)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=140)),
                ('tipo', models.CharField(max_length=140)),
                ('kilometraje', models.PositiveIntegerField()),
                ('nombre_propietario', models.CharField(max_length=140)),
                ('telefono_propietario', models.CharField(max_length=140)),
                ('estado', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='vehiculos.category')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('category', 'placa')},
            },
        ),
    ]
